@echo off
echo Iniciando React Native...
start cmd /k "cd /d apps\mobile && npx expo start -c"
echo Iniciando Backend Node...
start cmd /k "cd /d services\api && npx tsx src\server.ts"
echo Iniciando Backend ML...
start cmd /k "cd /d services\ml && uvicorn main:app --reload"
echo Tudo iniciado!