import { StyleSheet } from 'react-native';
import { colors, typography } from '@ludora/design-tokens';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.fundo,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardClaro,
  },
  headerBackBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: colors.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 14,
    letterSpacing: 0.5,
  },
  headerActionBtn: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borda,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center'
  },
  headerEditBtnText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 12,
  },
  headerEditBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borda,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  hero: {
    padding: 20,
    alignItems: 'center',
  },
  heroCatRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 28,
  },
  heroCatText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  heroDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.textoSecundario,
  },
  heroTeamsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  heroTeamCol: {
    flex: 1,
    alignItems: 'center',
    gap: 12,
  },
  logoTimeWrap: {
    width: 72,
    height: 72,
    borderRadius: 10,
    backgroundColor: colors.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoTimeImg: {
    width: 72,
    height: 72,
    borderRadius: 10,
    resizeMode: 'contain',
    backgroundColor: colors.card,
  },
  heroTeamName: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 12,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  heroScoreBlock: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    gap: 6,
  },
  liveScoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  scoreColumn: {
    alignItems: 'center',
    gap: 8,
  },
  stepBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: colors.primaria,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepBtnMinus: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borda,
  },
  heroScoreText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 32,
    lineHeight: 36,
  },
  heroScoreSeparatorDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.textoSecundario,
    marginTop: 4,
  },
  heroVs: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 16,
  },
  scheduledBadge: {
    paddingHorizontal: 14,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
    backgroundColor: colors.fundoBotao,
    borderColor: colors.primaria,
  },
  scheduledBadgeText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.primaria,
    fontSize: 11,
  },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.fundoErro,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.bordaErro,
    marginTop: 8,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.tituloErro,
  },
  liveBadgeText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.tituloErro,
    fontSize: 10,
    letterSpacing: 1,
  },
  finishedBadge: {
    backgroundColor: colors.card,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.borda,
    marginTop: 12,
  },
  finishedBadgeText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 10,
    letterSpacing: 1,
  },
  infoBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: colors.borda,
    borderBottomWidth: 1,
    borderBottomColor: colors.borda,
    marginBottom: 24,
  },
  infoBarItem: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  infoBarLabel: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 11,
  },
  infoBarValue: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 12,
    textAlign: 'center',
  },
  infoBarDivider: {
    width: 1,
    height: 40,
    backgroundColor: colors.borda,
  },
  section: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionBar: {
    width: 4,
    height: 16,
    borderRadius: 2,
    backgroundColor: colors.primaria,
  },
  sectionTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 12,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  // Controle de Período
  periodWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'transparent',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.primaria,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  periodBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: colors.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  periodBtnDisabled: {
    opacity: 0.5,
  },
  periodCenter: {
    alignItems: 'center',
    gap: 4,
  },
  periodTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.primaria,
    fontSize: typography.fontSize.md,
    letterSpacing: 1,
  },
  periodSub: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 11,
  },
  // Grid de Eventos
  eventsGrid: {
    gap: 10,
  },
  eventsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  eventCard: {
    flex: 1,
    backgroundColor: colors.card,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    gap: 12,
  },
  eventIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: colors.cardSecundario,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventLabel: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 11,
  },
  // Lista de Eventos e Stats
  rowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 8,
    gap: 12,
  },
  rowIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.cardSecundario,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 13,
  },
  rowSub: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 11,
    marginTop: 2,
  },
  statsBadgesWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.cardSecundario,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.primaria + '30',
  },
  statBadgeText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    fontSize: 11,
  },
  emptyStateBox: {
    alignItems: 'center',
    paddingVertical: 20,
    gap: 6,
  },
  emptyStateText: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 13,
    textAlign: 'center',
  },
  finalizarBtn: {
    backgroundColor: colors.primaria,
    borderRadius: 10,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  finalizarBtnText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: '#FFF',
    fontSize: 13,
    letterSpacing: 1,
  },
  finalizarSection: {
    paddingHorizontal: 20,
    marginTop: 10,
  },
  // ── MODAIS BASE ──
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: colors.fundo,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: colors.borda,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 24,
  },
  modalTitleText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 15,
    marginBottom: 2,
  },
  modalPeriodText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.primaria,
    fontSize: 11,
    marginBottom: 16,
    letterSpacing: 0.5,
  },
  modalSectionLabel: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 12,
    marginBottom: 12,
  },
  // ── MODAL GOL (PROTÓTIPO) ──
  modalSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 48,
    borderWidth: 1,
    borderColor: colors.borda,
    marginBottom: 16,
  },
  modalSearchInput: {
    flex: 1,
    marginLeft: 8,
    color: colors.texto,
    fontFamily: typography.fontFamily.corpo.regular,
    fontSize: 14,
  },
  golContraBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5C51810',
    borderWidth: 1,
    borderColor: '#F5C51840',
    borderRadius: 8,
    padding: 14,
    marginBottom: 24,
  },
  golContraIconWrap: {
    marginRight: 12,
  },
  golContraTitle: {
    color: '#F5C518',
    fontFamily: typography.fontFamily.corpo.semiBold,
    fontSize: 13,
  },
  golContraSub: {
    color: '#F5C51880',
    fontFamily: typography.fontFamily.corpo.regular,
    fontSize: 11,
    marginTop: 2,
  },
  jogadorSelectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: colors.borda,
    marginBottom: 8,
    gap: 12,
  },
  jogadorNumeroBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: colors.primaria,
    alignItems: 'center',
    justifyContent: 'center',
  },
  jogadorNumeroTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: '#FFF',
    fontSize: 14,
  },
  jogadorSelectNome: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 14,
  },
  jogadorSelectPos: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 11,
    marginTop: 2,
  },
  cancelLinkBtn: {
    marginTop: 16,
    alignItems: 'center',
    paddingVertical: 12,
  },
  cancelLinkText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 12,
    letterSpacing: 0.5,
  },
  saveStatBtn: {
    backgroundColor: colors.primaria,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  saveStatBtnText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: '#FFF',
    fontSize: 13,
    letterSpacing: 1,
  },
  modalJogadorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  // ── MODAL FINALIZAR (PROTÓTIPO) ──
  confirmOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  confirmBox: {
    width: '100%',
    backgroundColor: colors.fundo,
    borderRadius: 10,
    padding: 24,
    alignItems: 'center',
  },
  confirmIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.fundoErro,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  confirmTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 16,
    marginBottom: 8,
    textAlign: 'center',
  },
  confirmDesc: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 18,
  },
  confirmBtnRow: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  confirmCancelBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: colors.card,
    alignItems: 'center',
  },
  confirmCancelTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 12,
  },
  confirmOkBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: colors.fundoErro,
    alignItems: 'center',
  },
  confirmOkTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.tituloErro,
    fontSize: 12,
  },
  // ── MODAL DE EDIÇÃO DA PARTIDA ──
  editModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.borda,
    gap: 12,
  },
  editModalTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 17,
    letterSpacing: 0.5,
  },
  editModalSub: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 11,
    marginTop: 1,
  },
  localInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borda,
    paddingHorizontal: 12,
    paddingVertical: 14,
    gap: 8,
    marginBottom: 28,
  },
  localInputText: {
    flex: 1,
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.texto,
    fontSize: 14,
  },
  deletePartidaBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.bordaErro,
    backgroundColor: colors.fundoErro,
    marginBottom: 10,
  },
  deletePartidaTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.tituloErro,
    fontSize: 13,
    letterSpacing: 0.5,
  },
  modalHeaderTime: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitleTime: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 18,
  },
  closeBtnTime: {
    padding: 4,
  },
  buscaContainerTime: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.borda,
    height: 48,
    marginBottom: 16,
  },
  buscaTextTime: {
    flex: 1,
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.texto,
    fontSize: 14,
    marginLeft: 8,
  },
  modalItemTime: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    padding: 12,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.borda,
  },
  modalItemTimeActive: {
    backgroundColor: colors.fundoBotao,
    borderColor: colors.bordaBotao,
  },
  modalIconCircleTime: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.cardSecundario,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  modalItemTextTime: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 14,
    marginBottom: 2,
  },
  modalItemSubTime: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 12,
  },
  checkBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.primaria + '20',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionLabel: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 11,
    letterSpacing: 1,
    marginTop: 10,
    marginBottom: 10,
  },
  confrontoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  vsBadgeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.primaria,
    zIndex: 10,
    marginHorizontal: -20,
  },
  vsText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: '#FFF',
    fontSize: 11,
  },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borda,
    marginBottom: 20,
    overflow: 'hidden',
  },
  stepperValue: {
    flex: 1,
    alignItems: 'center',
  },
  stepperValueTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 18,
  },
  salvarBtn: {
    borderRadius: 10,
    overflow: 'hidden',
  },
  salvarGradient: {
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  salvarBtnInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  salvarText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: '#FFF',
    fontSize: 14,
    letterSpacing: 1,
  },
  subCategoriaText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 12,
    marginBottom: 16,
    textTransform: 'uppercase',
  },
  // ── ESTILOS RESTAURADOS (Confirmação e Editar) ──
  modalSubText: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 13,
    marginBottom: 16,
  },
  modalJogadorNum: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borda,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalJogadorNumText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 18,
  },
  modalJogadorNome: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 18,
  },
  modalJogadorPos: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 13,
  },
  stepperBtn: {
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperBtnDisabled: {
    opacity: 0.3,
  },
  modalContent: {
    backgroundColor: colors.fundo,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 40,
    maxHeight: '85%',
  },
});