import { StyleSheet } from 'react-native';
import { colors, typography } from '@ludora/design-tokens';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.fundo,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardClaro,
  },
  headerBackBtn: {
    padding: 4,
  },
  headerTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 14,
    letterSpacing: 1,
  },
  // ── HEADER ──
  headerEditBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.cardClaro,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerActionBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.cardClaro,
    backgroundColor: 'transparent',
    justifyContent: 'center',
  },
  headerEditBtnText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 12,
  },
  hero: {
    padding: 20,
    alignItems: 'center',
  },
  // ── HERO (Times, VS e Data) ──
  heroCatRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 28,
  },
  heroCatText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  heroDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.textoSecundario,
  },
  heroTeamsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  heroTeamCol: {
    flex: 1,
    alignItems: 'center',
    gap: 12,
  },
  logoTimeWrap: {
    width: 64,
    height: 64,
    borderRadius: 10,
    backgroundColor: colors.cardSecundario,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoTimeImg: {
    width: 64,
    height: 64,
    borderRadius: 10,
    resizeMode: 'contain',
    backgroundColor: colors.cardSecundario,
  },
  heroTeamName: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 13,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  heroScoreBlock: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    gap: 8,
  },
  heroScoreText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 36,
    lineHeight: 40,
  },
  heroScoreSeparator: {
    width: 12,
    height: 2,
    backgroundColor: colors.cardClaro,
    marginHorizontal: 12,
  },
  heroVs: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 16,
  },
  stepBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.cardClaro,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepBtnMinus: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
  scheduledBadge: {
    paddingHorizontal: 14,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.primaria,
    backgroundColor: colors.fundoBotao,
  },
  scheduledBadgeText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.primaria,
    fontSize: 12,
  },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.fundoErro,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.fundoErro,
    marginTop: 12,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.vermelho,
  },
  liveBadgeText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.vermelho,
    fontSize: 10,
    letterSpacing: 1,
  },
  finishedBadge: {
    backgroundColor: colors.card,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.cardClaro,
    marginTop: 12,
  },
  finishedBadgeText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 10,
    letterSpacing: 1,
  },
  // ── INFO BAR ──
  infoBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: colors.cardClaro,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardClaro,
    marginBottom: 24,
  },
  infoBarItem: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  infoBarLabel: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 11,
  },
  infoBarValue: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 12,
    textAlign: 'center',
  },
  infoBarDivider: {
    width: 1,
    height: 40,
    backgroundColor: colors.cardClaro,
  },
  section: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionBar: {
    width: 4,
    height: 16,
    borderRadius: 2,
    backgroundColor: colors.primaria,
  },
  sectionTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 12,
    letterSpacing: 1,
  },
  // ── BOTÃO INICIAR PARTIDA ──
  finalizarBtn: {
    backgroundColor: colors.primaria,
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  finalizarBtnText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: '#FFF',
    fontSize: 13,
    letterSpacing: 1,
  },
  finalizarSection: {
    paddingHorizontal: 20,
    marginTop: 10,
  },
  // Controles de Período
  periodWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.cardClaro,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  periodBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.fundoBotao,
    borderWidth: 1,
    borderColor: colors.fundoBotao,
    alignItems: 'center',
    justifyContent: 'center',
  },
  periodBtnDisabled: {
    backgroundColor: colors.cardSecundario,
    borderColor: colors.cardClaro,
  },
  periodCenter: {
    alignItems: 'center',
    gap: 4,
  },
  periodTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.primaria,
    fontSize: typography.fontSize.md,
    letterSpacing: 1,
  },
  periodSub: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 11,
  },
  // Grid de Eventos
  eventsGrid: {
    gap: 10,
  },
  eventsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  eventCard: {
    flex: 1,
    backgroundColor: colors.card,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.cardClaro,
    gap: 8,
  },
  eventIconWrap: {
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventLabel: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 11,
  },
  // Lista de Eventos e Stats
  rowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: colors.cardClaro,
    gap: 10,
  },
  rowIconBox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: colors.cardSecundario,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 13,
  },
  rowSub: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 11,
  },
  statsBadgesWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    justifyContent: 'flex-end',
    maxWidth: 160,
  },
  statBadgeWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderWidth: 1,
  },
  statBadgeText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    fontSize: 11,
  },
  emptyStateBox: {
    alignItems: 'center',
    paddingVertical: 20,
    gap: 6,
  },
  emptyStateText: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 13,
    textAlign: 'center',
  },
  // Modais Base
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: colors.fundo,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 40,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#333',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  modalTitleText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 16,
    marginBottom: 4,
  },
  modalSubText: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 13,
    marginBottom: 16,
  },
  modalPeriodText: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.primaria,
    fontSize: 12,
    marginBottom: 16,
  },
  divider: {
    height: 1,
    backgroundColor: colors.cardClaro,
    marginBottom: 12,
  },
  // Modal de Jogador
  modalJogadorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  modalJogadorNum: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.cardClaro,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalJogadorNumText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 18,
  },
  modalJogadorNome: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 18,
  },
  modalJogadorPos: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 13,
  },
  jogadorSelectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: colors.cardClaro,
    gap: 12,
  },
  jogadorNumero: {
    backgroundColor: colors.cardSecundario,
    alignItems: 'center',
    justifyContent: 'center',
  },
  jogadorNumeroText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 14,
  },
  jogadorSelectNome: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 14,
  },
  jogadorSelectPos: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 11,
  },
  saveStatBtn: {
    backgroundColor: colors.primaria,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveStatBtnText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: '#FFF',
    fontSize: 13,
    letterSpacing: 1,
  },
  cancelLinkBtn: {
    marginTop: 12,
    alignItems: 'center',
    paddingVertical: 12,
  },
  cancelLinkText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 13,
  },
  // Modal Finalizar/Deletar (ConfirmBox)
  confirmOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  confirmBox: {
    width: '100%',
    backgroundColor: colors.fundo,
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
  },
  confirmIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.fundoErro,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  confirmTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 20,
    marginBottom: 8,
    textAlign: 'center',
  },
  confirmDesc: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 24,
  },
  confirmBtnRow: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  confirmCancel: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: colors.cardSecundario,
    alignItems: 'center',
  },
  confirmCancelText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 13,
  },
  confirmOk: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: colors.vermelho,
    alignItems: 'center',
  },
  confirmOkText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: '#FFF',
    fontSize: 13,
  },
  // Edit Partida Modal Specs
  editModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardClaro,
    gap: 12,
  },
  editModalTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 17,
    letterSpacing: 0.5,
  },
  editModalSub: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 11,
    marginTop: 1,
  },
  localInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.cardClaro,
    paddingHorizontal: 12,
    paddingVertical: 14,
    gap: 8,
    marginBottom: 28,
  },
  localInputText: {
    flex: 1,
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.texto,
    fontSize: 14,
  },
  deletePartidaBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.fundoErro,
    backgroundColor: colors.fundoErro,
  },
  deletePartidaTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.tituloErro,
    fontSize: 13,
    letterSpacing: 0.5,
  },
  // Modal de Busca de Times (Padronizado)
  modalHeaderTime: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitleTime: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 18,
  },
  closeBtnTime: {
    padding: 4,
  },
  buscaContainerTime: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.cardClaro,
    height: 48,
    marginBottom: 16,
  },
  buscaTextTime: {
    flex: 1,
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.texto,
    fontSize: 14,
    marginLeft: 8,
  },
  modalItemTime: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    padding: 12,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.cardClaro,
  },
  modalItemTimeActive: {
    backgroundColor: colors.fundoBotao,
    borderColor: colors.fundoBotao,
  },
  modalIconCircleTime: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.cardSecundario,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  modalItemTextTime: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 14,
    marginBottom: 2,
  },
  modalItemSubTime: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 12,
  },
  checkBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.primaria + '20',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // ── Estilos Faltantes do Modal de Editar Partida ──
  sectionLabel: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 11,
    letterSpacing: 1,
    marginTop: 10,
    marginBottom: 10,
  },
  confrontoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  vsBadgeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.primaria,
    zIndex: 10,
    marginHorizontal: -20,
  },
  vsText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: '#FFF',
    fontSize: 11,
  },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.cardClaro,
    marginBottom: 20,
    overflow: 'hidden',
  },
  stepperBtn: {
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperBtnDisabled: {
    opacity: 0.3,
  },
  stepperValue: {
    flex: 1,
    alignItems: 'center',
  },
  stepperValueTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 18,
  },
  salvarBtn: {
    borderRadius: 10,
    overflow: 'hidden',
  },
  salvarGradient: {
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  salvarBtnInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  salvarText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: '#FFF',
    fontSize: 14,
    letterSpacing: 1,
  },
  modalContent: {
    backgroundColor: colors.fundo,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 40,
    maxHeight: '85%',
  },
  subCategoriaText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 12,
    marginBottom: 16,
    textTransform: 'uppercase',
  }
});