import { StyleSheet } from 'react-native';
import { colors, typography } from '@ludora/design-tokens';

export const styles = StyleSheet.create({
  // ── SEÇÃO PRINCIPAL (Na tela de Detalhes) ──
  section: {
    paddingHorizontal: 20, // <- Aqui está a correção do "grudado na tela"!
    paddingVertical: 0,
    marginTop: 0,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionBar: {
    width: 4,
    height: 16,
    borderRadius: 2,
    backgroundColor: colors.primaria,
  },
  sectionTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 12,
    letterSpacing: 1,
  },
  sectionActionBtn: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.primaria,
    fontSize: 12,
    letterSpacing: 0.5,
  },
  sectionSubLabel: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 10,
    letterSpacing: 1,
    marginBottom: 12,
    marginTop: 8,
  },
  emptyBox: {
    alignItems: 'center',
    paddingVertical: 20,
    gap: 8,
  },
  emptyTxt: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 13,
  },
  emptyBtn: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: colors.primaria,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  emptyBtnTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.primaria,
    fontSize: 12,
  },

  // ── LINHA DE JOGADOR (JogadorRow) ──
  rowItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.borda,
    gap: 12,
  },
  rowItemTitular: {
    borderColor: colors.bordaBotao,
  },
  rowNumBox: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: colors.cardSecundario,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowNumTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 14,
  },
  rowNome: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 14,
  },
  rowPos: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 11,
    marginTop: 2,
  },
  rowBadge: {
    backgroundColor: 'transparent',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.primaria,
  },
  rowBadgeTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.primaria,
    fontSize: 10,
  },

  // ── MODAL PRINCIPAL (Escalação / Substituição) ──
  modalRoot: {
    flex: 1,
    backgroundColor: colors.fundo,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.borda,
  },
  modalTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 15,
    letterSpacing: 1,
  },
  modalCounterBox: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 2,
  },
  modalCounterNum: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.primaria,
    fontSize: 22,
  },
  modalCounterSep: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 16,
  },
  modalCounterMax: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 16,
  },
  modalDicaBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.borda,
  },
  modalDicaTxt: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 12,
    flex: 1,
  },
  modalEmptyBox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingHorizontal: 32,
  },
  modalEmptyTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 14,
    textAlign: 'center',
  },
  modalEmptySubTxt: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 12,
    textAlign: 'center',
  },
  modalSubHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    marginTop: 20,
  },
  modalSubDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  modalSubTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 12,
    letterSpacing: 1,
    flex: 1,
  },
  modalSubCount: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 12,
  },

  // ── CARDS DO MODAL ──
  cardTitular: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.fundoBotao,
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.bordaBotao,
  },
  cardBanco: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.borda,
  },
  cardBancoConvocado: {
    backgroundColor: colors.fundoBotao,
    borderColor: colors.bordaBotao,
  },
  cardOrdem: {
    width: 26,
    height: 26,
    borderRadius: 6,
    backgroundColor: colors.cardSecundario,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardOrdemNum: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.primaria,
    fontSize: 12,
  },
  cardCamisa: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.primaria,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardCamisaNum: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 14,
  },
  cardNome: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 14,
  },
  cardPos: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 11,
    marginTop: 2,
  },
  tagTitular: {
    backgroundColor: colors.primaria,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  tagTitularTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 10,
  },
  tagBanco: {
    backgroundColor: colors.cardSecundario,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  tagBancoTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 10,
  },
  slotVazio: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.borda,
    borderStyle: 'dashed',
  },
  fundoSubstituicao: {
    padding: 6
  },
  slotVazioTxt: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 12,
  },
  salvarBtn: {
    margin: 20,
    backgroundColor: colors.primaria,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  salvarBtnTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: '#FFF',
    fontSize: 14,
    letterSpacing: 1,
  },

  // ── MODAL DE EDITAR CAMISA ──
  mcOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  mcBox: {
    backgroundColor: colors.fundo,
    borderRadius: 24,
    padding: 24,
    width: '100%',
    borderWidth: 1,
    borderColor: colors.borda,
  },
  mcTitulo: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 16,
    marginBottom: 4,
  },
  mcSub: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 13,
    marginBottom: 16,
  },
  mcInput: {
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borda,
    color: colors.texto,
    fontFamily: typography.fontFamily.corpo.semiBold,
    fontSize: 24,
    paddingVertical: 14,
    paddingHorizontal: 16,
    textAlign: 'center',
    marginBottom: 20,
  },
  mcBtnRow: {
    flexDirection: 'row',
    gap: 12,
  },
  mcBtnCancel: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: colors.cardSecundario,
    alignItems: 'center',
  },
  mcBtnCancelTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 13,
  },
  mcBtnSave: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: colors.primaria,
    alignItems: 'center',
  },
  mcBtnSaveTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: '#FFF',
    fontSize: 13,
  },

  // ── MODAL DE TROCA DE CAMISA ──
  mtOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  mtBox: {
    backgroundColor: colors.fundo,
    borderRadius: 24,
    padding: 24,
    width: '100%',
    borderWidth: 1,
    borderColor: colors.borda,
    alignItems: 'center',
  },
  mtIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: colors.cardSecundario,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  mtTitulo: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 18,
    marginBottom: 8,
    textAlign: 'center',
  },
  mtDesc: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  mtBold: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
  },
  mtTrocaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 28,
    width: '100%',
  },
  mtCard: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.borda,
  },
  mtBadge: {
    backgroundColor: colors.cardSecundario,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  mtBadgeNum: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.primaria,
    fontSize: 20,
  },
  mtCardNome: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 12,
    textAlign: 'center',
  },
  mtBtnRow: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  mtBtnCancel: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: colors.cardSecundario,
    alignItems: 'center',
  },
  mtBtnCancelTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 13,
  },
  mtBtnConfirm: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: colors.primaria,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
  },
  mtBtnConfirmTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: '#FFF',
    fontSize: 13,
    letterSpacing: 0.5,
  }
});