import { StyleSheet } from 'react-native';
import { colors, typography } from '@ludora/design-tokens';

const MARGEM = 20;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.fundo,
  },
  containerCarregandoPermissao: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.fundo,
  },
  centralizado: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingHorizontal: 40,
    paddingBottom: 80,
  },
  estadoIcone: {
    width: 56,
    height: 56,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borda,
  },

  // Busca e cabeçalho da lista
  buscaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 48,
    marginHorizontal: MARGEM,
    marginTop: 4,
    marginBottom: 14,
    paddingHorizontal: 14,
    gap: 10,
    backgroundColor: colors.card,
    borderRadius: 10,

  },
  buscaInput: {
    flex: 1,
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.texto,
    fontSize: typography.fontSize.sm,
  },
  listaHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MARGEM,
    marginBottom: 10,
  },
  listaTitulo: {
    fontFamily: typography.fontFamily.titulo.semiBold,
    color: colors.texto,
    fontSize: typography.fontSize.md,
    letterSpacing: 0.4,
  },
  listaContador: {
    fontFamily: typography.fontFamily.corpo.medium,
    color: colors.textoSecundario,
    fontSize: 11,
    letterSpacing: 0.4,
  },
  listaContent: {
    paddingHorizontal: MARGEM,
    paddingBottom: 100,
  },
  telaContent: {
    paddingTop: 4,
    paddingBottom: 110,
  },
  listaVazia: {
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 40,
    paddingVertical: 44,
  },
  txtErro: {
    fontFamily: typography.fontFamily.corpo.medium,
    color: colors.textoSecundario,
    fontSize: typography.fontSize.sm,
    lineHeight: 20,
    textAlign: 'center',
  },
  btnRetry: {
    backgroundColor: colors.fundoBotao,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderWidth: 1,
    borderColor: colors.bordaBotao,
  },
  txtBtnRetry: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.primaria,
    fontSize: typography.fontSize.sm,
  },

  // Card do atleta
  cardJogador: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.card,
    borderRadius: 10,
    padding: 14,
    marginHorizontal: MARGEM,
    marginBottom: 10,
  },
  cardNumCamisa: {
    width: 46,
    height: 46,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.cardSecundario,
  },
  cardNumCamisaTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    fontSize: typography.fontSize.sm,
  },
  cardInfos: {
    flex: 1,
    minWidth: 0,
  },
  cardNome: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: typography.fontSize.sm,
  },
  cardSub: {
    marginTop: 3,
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: typography.fontSize.xs,
  },
  cardDireita: {
    alignItems: 'flex-end',
  },
  cardBadgePerfil: {
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 5,
    borderWidth: 1,
    marginBottom: 5,
  },
  cardBadgePerfilTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    fontSize: 10,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  cardNotaLabel: {
    fontFamily: typography.fontFamily.corpo.medium,
    color: colors.textoSecundario,
    fontSize: 10,
    letterSpacing: 0.6,
  },
  cardNota: {
    fontFamily: typography.fontFamily.titulo.semiBold,
    color: colors.texto,
    fontSize: typography.fontSize.lmd,
    lineHeight: 22,
  },

  // Ficha do atleta
  scoutContainer: {
    flex: 1,
    backgroundColor: colors.fundo,
  },
  scoutContent: {
    paddingHorizontal: MARGEM,
    paddingTop: 8,
    paddingBottom: 40,
  },
  scoutIdentidade: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: colors.card,
    borderRadius: 10,
    padding: 16,
    borderWidth: 1,
    marginBottom: 18,
  },
  scoutAvatarNum: {
    width: 56,
    height: 56,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scoutAvatarNumTxt: {
    fontFamily: typography.fontFamily.titulo.bold,
    fontSize: typography.fontSize.xl,
  },
  scoutNome: {
    fontFamily: typography.fontFamily.titulo.semiBold,
    color: colors.texto,
    fontSize: typography.fontSize.lg,
  },
  scoutPosicao: {
    marginTop: 1,
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: typography.fontSize.xs,
  },
  scoutPerfilDescricao: {
    marginTop: 8,
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: typography.fontSize.xs,
    lineHeight: 17,
  },
  scoutChip: {
    backgroundColor: colors.cardSecundario,
    borderRadius: 5,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: colors.borda,
  },
  scoutChipTxt: {
    fontFamily: typography.fontFamily.corpo.medium,
    color: colors.textoSecundario,
    fontSize: 10,
    textTransform: 'uppercase',
  },
  scoutNotaContainer: {
    alignItems: 'center',
    paddingLeft: 4,
  },
  scoutNotaLabel: {
    fontFamily: typography.fontFamily.corpo.medium,
    color: colors.textoSecundario,
    fontSize: 10,
    letterSpacing: 0.8,
  },
  scoutNota: {
    fontFamily: typography.fontFamily.titulo.bold,
    fontSize: typography.fontSize.xxl,
    lineHeight: 38,
  },

  // Radar e atributos
  scoutHexContainer: {
    alignItems: 'center',
    marginBottom: 22,
    paddingHorizontal: 16,
    paddingVertical: 18,
    backgroundColor: colors.card,
    borderRadius: 10,
  },
  scoutSecaoLabel: {
    alignSelf: 'flex-start',
    fontFamily: typography.fontFamily.titulo.semiBold,
    color: colors.texto,
    fontSize: typography.fontSize.md,
    letterSpacing: 0.5,
    marginBottom: 14,
    marginTop: 2,
  },
  scoutScoresGrid: {
    width: '100%',
    marginTop: 16,
    gap: 12,
  },
  scoutRadarNota: {
    marginTop: 4,
    paddingHorizontal: 8,
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: typography.fontSize.xs,
    lineHeight: 17,
    textAlign: 'center',
  },
  scoutScoreItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  scoutScoreLabel: {
    width: 92,
    fontFamily: typography.fontFamily.corpo.medium,
    color: colors.textoSecundario,
    fontSize: 10,
  },
  scoutScoreBarBg: {
    flex: 1,
    height: 6,
    backgroundColor: colors.cardSecundario,
    borderRadius: 3,
    overflow: 'hidden',
  },
  scoutScoreBar: {
    height: 6,
    borderRadius: 3,
  },
  scoutScoreVal: {
    width: 28,
    fontFamily: typography.fontFamily.corpo.semiBold,
    fontSize: typography.fontSize.xs,
    textAlign: 'right',
  },
  scoutSemDados: {
    alignItems: 'center',
    gap: 10,
    marginBottom: 22,
    paddingVertical: 32,
    paddingHorizontal: 20,
    backgroundColor: colors.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borda,
  },
  scoutSemDadosTxt: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: typography.fontSize.xs,
    lineHeight: 18,
    textAlign: 'center',
  },

  // Estatísticas e eficiência
  scoutStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 22,
  },
  scoutStatCard: {
    flexBasis: '30%',
    flexGrow: 1,
    maxWidth: '31.5%',
    minHeight: 112,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 16,
    backgroundColor: colors.card,
    borderRadius: 10,
  },
  scoutStatValor: {
    marginTop: 7,
    fontFamily: typography.fontFamily.titulo.semiBold,
    color: colors.texto,
    fontSize: typography.fontSize.xl,
  },
  scoutStatLabel: {
    marginTop: 2,
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: typography.fontSize.xs,
    textAlign: 'center',
  },
  scoutEficienciaRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  scoutEficienciaCard: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    backgroundColor: colors.card,
    borderRadius: 10,
  },
  scoutEficienciaValor: {
    marginTop: 7,
    fontFamily: typography.fontFamily.titulo.semiBold,
    color: colors.texto,
    fontSize: typography.fontSize.xl,
  },
  scoutEficienciaLabel: {
    marginTop: 2,
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: typography.fontSize.xs,
  },

  // Resumo e ordenação da categoria
  resumoContainer: {
    marginHorizontal: MARGEM,
    marginBottom: 14,
  },
  resumoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  resumoTitulo: {
    fontFamily: typography.fontFamily.titulo.semiBold,
    color: colors.texto,
    fontSize: typography.fontSize.md,
    letterSpacing: 0.4,
  },
  resumoSub: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.primaria,
    fontSize: typography.fontSize.xs,
    textTransform: 'uppercase',
  },
  resumoCards: {
    flexDirection: 'row',
    gap: 8,
  },
  resumoCard: {
    flex: 1,
    minWidth: 0,
    minHeight: 120,
    alignItems: 'flex-start',
    padding: 12,
    backgroundColor: colors.card,
    borderRadius: 10,

  },
  resumoCardLabel: {
    marginTop: 8,
    fontFamily: typography.fontFamily.corpo.medium,
    color: colors.textoSecundario,
    fontSize: 10,
    letterSpacing: 0.4,
  },
  resumoCardValor: {
    fontFamily: typography.fontFamily.titulo.semiBold,
    color: colors.texto,
    fontSize: typography.fontSize.xl,
    lineHeight: 29,
  },
  resumoCardNome: {
    width: '100%',
    marginTop: 1,
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 11,
  },
  infoAnalise: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
    marginHorizontal: MARGEM,
    marginBottom: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: colors.fundoBotao,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.bordaBotao,
  },
  infoAnaliseTxt: {
    flex: 1,
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: typography.fontSize.xs,
    lineHeight: 18,
  },
  ordenacaoContent: {
    paddingHorizontal: MARGEM,
    paddingBottom: 14,
    gap: 8,
  },
  ordenacaoPill: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: colors.card,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: colors.borda,
  },
  ordenacaoPillAtiva: {
    backgroundColor: colors.fundoBotao,
    borderColor: colors.bordaBotao,
  },
  ordenacaoTxt: {
    fontFamily: typography.fontFamily.corpo.medium,
    color: colors.textoSecundario,
    fontSize: typography.fontSize.xs,
  },
  ordenacaoTxtAtiva: {
    color: colors.primaria,
  },
});
