import { StyleSheet } from 'react-native';
import { colors, typography } from '@ludora/design-tokens';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.fundo,
  },
  content: {
    paddingHorizontal: 20,
  },
  editBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardSecundario,
    padding: 12,
    gap: 8,
  },
  editBannerTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 12,
  },
  sectionLabel: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 11,
    letterSpacing: 1,
    marginTop: 24,
    marginBottom: 12,
  },
  categoriaLocked: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    padding: 14,
    borderRadius: 10,
    gap: 8,
    borderWidth: 1,
    borderColor: colors.borda,
  },
  categoriaLockedNome: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 14,
  },
  categoriaLockedSub: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 11,
    marginLeft: 'auto',
  },
  pillRow: {
    gap: 10,
  },
  pill: {
    backgroundColor: colors.card,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borda,
  },
  pillActive: {
    backgroundColor: colors.primaria,
    borderColor: colors.primaria,
  },
  pillText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 12,
  },
  pillTextActive: {
    color: '#FFF',
  },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borda,
  },
  stepperBtn: {
    padding: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperBtnAtivo: {
    opacity: 1,
  },
  stepperBtnDisabled: {
    opacity: 0.3,
  },
  stepperDivider: {
    width: 1,
    height: '60%',
    backgroundColor: colors.borda,
  },
  stepperValue: {
    flex: 1,
    alignItems: 'center',
  },
  stepperValueTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 16,
  },
  stepperValueZero: {
    color: colors.textoSecundario,
  },
  grupoPill: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    backgroundColor: colors.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borda,
  },
  grupoPillAtivo: {
    backgroundColor: colors.fundoBotao,
    borderColor: colors.primaria,
  },
  grupoPillTxt: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
  },
  grupoPillTxtAtivo: {
    color: colors.primaria,
  },
  confrontoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  vsBadgeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.primaria,
    zIndex: 10,
    marginHorizontal: -20,
  },
  vsText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: '#FFF',
    fontSize: 11,
  },
  resumoCard: {
    backgroundColor: colors.card,
    padding: 16,
    borderRadius: 12,
    gap: 8,
    marginTop: 20,
    borderWidth: 1,
    borderColor: colors.borda,
  },
  resumoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  resumoTxt: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.texto,
    fontSize: 12,
  },
  salvarBtn: {
    borderRadius: 10,
    overflow: 'hidden',
  },
  salvarGradient: {
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  salvarBtnInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  salvarText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: '#FFF',
    fontSize: 14,
  },
  loadingTxt: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 13,
  },
  // Modais de Seleção (Copiados do OrganizarPartidas)
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.fundo,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 40,
    maxHeight: '85%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 18,
  },
  closeBtn: {
    padding: 4,
  },
  buscaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.borda,
    height: 48,
    marginBottom: 16,
  },
  buscaText: {
    flex: 1,
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.texto,
    fontSize: 14,
    marginLeft: 8,
  },
  subCategoriaText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.textoSecundario,
    fontSize: 12,
    marginBottom: 16,
    textTransform: 'uppercase',
  },
  modalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    padding: 12,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.borda,
  },
  modalItemActive: {
    backgroundColor: colors.fundoBotao,
    borderColor: colors.bordaBotao,
  },
  modalIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.cardSecundario,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  modalItemText: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.texto,
    fontSize: 14,
    marginBottom: 2,
  },
  modalItemSub: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.textoSecundario,
    fontSize: 12,
  },
  // Fila de Partidas
  filaPendenteAlerta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: colors.fundoBotao,
    borderBottomWidth: 1,
    borderBottomColor: colors.bordaBotao,
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  filaBadgeNum: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.primaria,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filaPendenteTexto: {
    fontFamily: typography.fontFamily.corpo.semiBold,
    color: colors.primaria,
    fontSize: 12,
    letterSpacing: 0.5,
    flex: 1,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.borda,
    height: 48,
  },
  inputText: {
    fontFamily: typography.fontFamily.corpo.regular,
    color: colors.texto,
    fontSize: 14,
    marginLeft: 8,
  },
});