/* AUTO-GENERATED by scripts/generate-icons.mjs. Do not edit manually. */
import { AddIcon } from './icons/AddIcon';
import { LiveIcon } from './icons/LiveIcon';
import { WhistleIcon } from './icons/WhistleIcon';
import { FlagIcon } from './icons/FlagIcon';
import { BallIcon } from './icons/BallIcon';
import { SearchIcon } from './icons/SearchIcon';
import { CalendarIcon } from './icons/CalendarIcon';
import { CheckIcon } from './icons/CheckIcon';
import { ChevronRightIcon } from './icons/ChevronRightIcon';
import { ChevronLeftIcon } from './icons/ChevronLeftIcon';
import { CleatIcon } from './icons/CleatIcon';
import { BadgeIcon } from './icons/BadgeIcon';
import { EmailIcon } from './icons/EmailIcon';
import { ShieldHalfIcon } from './icons/ShieldHalfIcon';
import { ShieldIcon } from './icons/ShieldIcon';
import { CloseIcon } from './icons/CloseIcon';
import { FilterIcon } from './icons/FilterIcon';
import { GroupIcon } from './icons/GroupIcon';
import { HomeIcon } from './icons/HomeIcon';
import { IdCardIcon } from './icons/IdCardIcon';
import { InfoIcon } from './icons/InfoIcon';
import { EditIcon } from './icons/EditIcon';
import { TrashIcon } from './icons/TrashIcon';
import { LocationIcon } from './icons/LocationIcon';
import { VisibilityOffIcon } from './icons/VisibilityOffIcon';
import { PlayCircleIcon } from './icons/PlayCircleIcon';
import { PodiumIcon } from './icons/PodiumIcon';
import { BoltIcon } from './icons/BoltIcon';
import { ClockIcon } from './icons/ClockIcon';
import { PasswordIcon } from './icons/PasswordIcon';
import { ArrowRightIcon } from './icons/ArrowRightIcon';
import { ArrowLeftIcon } from './icons/ArrowLeftIcon';
import { TrophyIcon } from './icons/TrophyIcon';
import { UserIcon } from './icons/UserIcon';
import { VerifiedIcon } from './icons/VerifiedIcon';
import { AccountOffIcon } from './icons/AccountOffIcon';
import { AccountPlusIcon } from './icons/AccountPlusIcon';
import { AlertCircleIcon } from './icons/AlertCircleIcon';
import { ArrowDownCircleIcon } from './icons/ArrowDownCircleIcon';
import { ArrowUpCircleIcon } from './icons/ArrowUpCircleIcon';
import { ArrowUpCircleOutlineIcon } from './icons/ArrowUpCircleOutlineIcon';
import { BellIcon } from './icons/BellIcon';
import { BellOutlineIcon } from './icons/BellOutlineIcon';
import { BusIcon } from './icons/BusIcon';
import { BusSideIcon } from './icons/BusSideIcon';
import { CalendarClockIcon } from './icons/CalendarClockIcon';
import { CalendarEditIcon } from './icons/CalendarEditIcon';
import { CalendarRemoveIcon } from './icons/CalendarRemoveIcon';
import { CameraPlusIcon } from './icons/CameraPlusIcon';
import { CardIcon } from './icons/CardIcon';
import { ChartArcIcon } from './icons/ChartArcIcon';
import { CheckAllIcon } from './icons/CheckAllIcon';
import { CheckCircleIcon } from './icons/CheckCircleIcon';
import { CheckCircleOutlineIcon } from './icons/CheckCircleOutlineIcon';
import { CheckboxBlankIcon } from './icons/CheckboxBlankIcon';
import { CheckboxMarkedIcon } from './icons/CheckboxMarkedIcon';
import { ChevronDownIcon } from './icons/ChevronDownIcon';
import { ChevronUpIcon } from './icons/ChevronUpIcon';
import { CircleOutlineIcon } from './icons/CircleOutlineIcon';
import { ClipboardCheckIcon } from './icons/ClipboardCheckIcon';
import { ClipboardTextIcon } from './icons/ClipboardTextIcon';
import { CloseCircleIcon } from './icons/CloseCircleIcon';
import { CloudUploadIcon } from './icons/CloudUploadIcon';
import { SaveEditIcon } from './icons/SaveEditIcon';
import { DotsHorizontalIcon } from './icons/DotsHorizontalIcon';
import { VisibilityIcon } from './icons/VisibilityIcon';
import { FileUploadIcon } from './icons/FileUploadIcon';
import { HandBackRightIcon } from './icons/HandBackRightIcon';
import { GoalkeeperHandIcon } from './icons/GoalkeeperHandIcon';
import { HandshakeIcon } from './icons/HandshakeIcon';
import { LogoutIcon } from './icons/LogoutIcon';
import { MedalIcon } from './icons/MedalIcon';
import { MinusIcon } from './icons/MinusIcon';
import { PlusCircleIcon } from './icons/PlusCircleIcon';
import { RadarIcon } from './icons/RadarIcon';
import { RecordCircleIcon } from './icons/RecordCircleIcon';
import { RunFastIcon } from './icons/RunFastIcon';
import { ShieldCheckIcon } from './icons/ShieldCheckIcon';
import { ShieldOffIcon } from './icons/ShieldOffIcon';
import { ShieldSearchIcon } from './icons/ShieldSearchIcon';
import { ShieldStarIcon } from './icons/ShieldStarIcon';
import { SoccerFieldIcon } from './icons/SoccerFieldIcon';
import { StarIcon } from './icons/StarIcon';
import { StarOutlineIcon } from './icons/StarOutlineIcon';
import { SwapHorizontalIcon } from './icons/SwapHorizontalIcon';
import { ShirtIcon } from './icons/ShirtIcon';
import { ShirtOutlineIcon } from './icons/ShirtOutlineIcon';
import { WifiOffIcon } from './icons/WifiOffIcon';
import type { LudoraIconProps } from './types';

const iconMap = {
  "add": AddIcon,
  "plus": AddIcon,
  "live": LiveIcon,
  "whistle": WhistleIcon,
  "flag": FlagIcon,
  "flag-variant": FlagIcon,
  "ball": BallIcon,
  "soccer": BallIcon,
  "search": SearchIcon,
  "magnify": SearchIcon,
  "calendar": CalendarIcon,
  "calendar-outline": CalendarIcon,
  "check": CheckIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-left": ChevronLeftIcon,
  "cleat": CleatIcon,
  "shoe-cleat": CleatIcon,
  "badge": BadgeIcon,
  "email": EmailIcon,
  "email-outline": EmailIcon,
  "shield-half": ShieldHalfIcon,
  "shield": ShieldIcon,
  "shield-outline": ShieldIcon,
  "close": CloseIcon,
  "filter": FilterIcon,
  "filter-variant": FilterIcon,
  "group": GroupIcon,
  "account-group-outline": GroupIcon,
  "home": HomeIcon,
  "home-outline": HomeIcon,
  "id-card": IdCardIcon,
  "card-account-details-outline": IdCardIcon,
  "info": InfoIcon,
  "information-outline": InfoIcon,
  "edit": EditIcon,
  "pencil-outline": EditIcon,
  "pencil-circle": EditIcon,
  "trash": TrashIcon,
  "trash-can-outline": TrashIcon,
  "location": LocationIcon,
  "map-marker-outline": LocationIcon,
  "visibility-off": VisibilityOffIcon,
  "eye-off-outline": VisibilityOffIcon,
  "play-circle": PlayCircleIcon,
  "play-circle-outline": PlayCircleIcon,
  "podium": PodiumIcon,
  "bolt": BoltIcon,
  "clock": ClockIcon,
  "clock-outline": ClockIcon,
  "password": PasswordIcon,
  "lock-outline": PasswordIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-left": ArrowLeftIcon,
  "trophy": TrophyIcon,
  "trophy-outline": TrophyIcon,
  "user": UserIcon,
  "account": UserIcon,
  "account-outline": UserIcon,
  "verified": VerifiedIcon,
  "check-decagram": VerifiedIcon,
  "account-off-outline": AccountOffIcon,
  "account-plus-outline": AccountPlusIcon,
  "alert-circle-outline": AlertCircleIcon,
  "arrow-down-circle": ArrowDownCircleIcon,
  "arrow-up-circle": ArrowUpCircleIcon,
  "arrow-up-circle-outline": ArrowUpCircleOutlineIcon,
  "bell": BellIcon,
  "bell-outline": BellOutlineIcon,
  "bus": BusIcon,
  "bus-side": BusSideIcon,
  "calendar-clock": CalendarClockIcon,
  "calendar-edit": CalendarEditIcon,
  "calendar-remove-outline": CalendarRemoveIcon,
  "camera-plus-outline": CameraPlusIcon,
  "card": CardIcon,
  "chart-arc": ChartArcIcon,
  "check-all": CheckAllIcon,
  "check-circle": CheckCircleIcon,
  "check-circle-outline": CheckCircleOutlineIcon,
  "checkbox-blank-outline": CheckboxBlankIcon,
  "checkbox-marked": CheckboxMarkedIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-up": ChevronUpIcon,
  "circle-outline": CircleOutlineIcon,
  "clipboard-check-outline": ClipboardCheckIcon,
  "clipboard-text-outline": ClipboardTextIcon,
  "close-circle": CloseCircleIcon,
  "cloud-upload-outline": CloudUploadIcon,
  "content-save-edit-outline": SaveEditIcon,
  "dots-horizontal": DotsHorizontalIcon,
  "eye-outline": VisibilityIcon,
  "file-upload-outline": FileUploadIcon,
  "hand-back-right": HandBackRightIcon,
  "hand-front-right": GoalkeeperHandIcon,
  "handshake": HandshakeIcon,
  "logout": LogoutIcon,
  "medal-outline": MedalIcon,
  "minus": MinusIcon,
  "plus-circle-outline": PlusCircleIcon,
  "radar": RadarIcon,
  "record-circle-outline": RecordCircleIcon,
  "run-fast": RunFastIcon,
  "shield-check": ShieldCheckIcon,
  "shield-off-outline": ShieldOffIcon,
  "shield-search": ShieldSearchIcon,
  "shield-star": ShieldStarIcon,
  "soccer-field": SoccerFieldIcon,
  "star": StarIcon,
  "star-outline": StarOutlineIcon,
  "swap-horizontal": SwapHorizontalIcon,
  "tshirt-crew": ShirtIcon,
  "tshirt-crew-outline": ShirtOutlineIcon,
  "wifi-off": WifiOffIcon,
} as const;

export type IconName = keyof typeof iconMap;
export type IconProps = LudoraIconProps & { name: IconName };

export function Icon({ name, ...props }: IconProps) {
  const IconComponent = iconMap[name];
  return <IconComponent {...props} />;
}
