import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const svgDir = join(packageRoot, 'src', 'svg');
const iconsDir = join(packageRoot, 'src', 'icons');
const manifestPath = join(packageRoot, 'scripts', 'icons.json');
const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
await mkdir(iconsDir, { recursive: true });

function attribute(source, name) {
  return source.match(new RegExp(`${name}=["']([^"']+)["']`, 'i'))?.[1];
}

function indent(value, spaces) {
  const prefix = ' '.repeat(spaces);
  return value.split('\n').map((line) => `${prefix}${line}`).join('\n');
}

function componentSource({ component, source }, svg) {
  const viewBox = attribute(svg, 'viewBox');
  if (!viewBox) throw new Error(`${source}: viewBox não encontrado`);

  const unsupported = svg.match(/<(circle|ellipse|line|polygon|polyline|rect|g)\b/i)?.[1];
  if (unsupported) {
    throw new Error(`${source}: elemento <${unsupported}> ainda não é suportado pelo gerador`);
  }

  const paths = [...svg.matchAll(/<path\b([^>]*)\/?\s*>/gi)].map((match) => {
    const d = attribute(match[1], 'd');
    if (!d) throw new Error(`${source}: <path> sem atributo d`);
    return `<Path fill={color} d=${JSON.stringify(d)} />`;
  });
  if (!paths.length) throw new Error(`${source}: nenhum <path> encontrado`);

  const notice = svg.match(/<!--([\s\S]*?)-->/)?.[1].trim();
  const noticeComment = notice ? `// Source notice: ${notice.replace(/\s+/g, ' ')}\n` : '';

  return `/* AUTO-GENERATED by scripts/generate-icons.mjs. Do not edit manually. */
${noticeComment}import Svg, { Path } from 'react-native-svg';

import type { LudoraIconProps } from '../types';

export function ${component}({
  size = 24,
  color = '#FFFFFF',
  accessibilityLabel,
  ...svgProps
}: LudoraIconProps) {
  return (
    <Svg
      width={size}
      height={size}
      viewBox=${JSON.stringify(viewBox)}
      accessibilityRole="image"
      accessibilityLabel={accessibilityLabel}
      {...svgProps}
    >
${indent(paths.join('\n'), 6)}
    </Svg>
  );
}
`;
}

const svgFiles = (await readdir(svgDir)).filter((file) => file.endsWith('.svg')).sort();
const declaredFiles = manifest.map((icon) => icon.source).sort();
const missingFromManifest = svgFiles.filter((file) => !declaredFiles.includes(file));
const missingFromDisk = declaredFiles.filter((file) => !svgFiles.includes(file));

if (missingFromManifest.length || missingFromDisk.length) {
  throw new Error([
    missingFromManifest.length ? `SVGs sem entrada no manifesto: ${missingFromManifest.join(', ')}` : '',
    missingFromDisk.length ? `Entradas sem SVG: ${missingFromDisk.join(', ')}` : '',
  ].filter(Boolean).join('\n'));
}

const components = new Set();
const names = new Set();
for (const icon of manifest) {
  if (components.has(icon.component)) throw new Error(`Componente duplicado: ${icon.component}`);
  const publicNames = [icon.name, ...(icon.aliases ?? [])];
  const duplicateName = publicNames.find((name) => names.has(name));
  if (duplicateName) throw new Error(`Nome público duplicado: ${duplicateName}`);
  components.add(icon.component);
  publicNames.forEach((name) => names.add(name));

  const svg = await readFile(join(svgDir, icon.source), 'utf8');
  await writeFile(join(iconsDir, `${icon.component}.tsx`), componentSource(icon, svg), 'utf8');
}

const iconImports = manifest
  .map(({ component }) => `import { ${component} } from './icons/${component}';`)
  .join('\n');
const iconMap = manifest
  .flatMap(({ component, name, aliases = [] }) =>
    [name, ...aliases].map((publicName) => `  ${JSON.stringify(publicName)}: ${component},`),
  )
  .join('\n');

await writeFile(join(packageRoot, 'src', 'Icon.tsx'), `/* AUTO-GENERATED by scripts/generate-icons.mjs. Do not edit manually. */
${iconImports}
import type { LudoraIconProps } from './types';

const iconMap = {
${iconMap}
} as const;

export type IconName = keyof typeof iconMap;
export type IconProps = LudoraIconProps & { name: IconName };

export function Icon({ name, ...props }: IconProps) {
  const IconComponent = iconMap[name];
  return <IconComponent {...props} />;
}
`, 'utf8');

const exports = manifest
  .map(({ component }) => `export { ${component} } from './icons/${component}';`)
  .join('\n');

await writeFile(join(packageRoot, 'src', 'index.ts'), `/* AUTO-GENERATED by scripts/generate-icons.mjs. Do not edit manually. */
${exports}
export { Icon } from './Icon';
export type { IconName, IconProps } from './Icon';
export type { LudoraIconProps } from './types';
`, 'utf8');

console.log(`${manifest.length} ícones gerados com sucesso.`);
