/* AUTO-GENERATED by scripts/generate-icons.mjs. Do not edit manually. */
import Svg, { Path } from 'react-native-svg';

import type { LudoraIconProps } from '../types';

export function BellIcon({
  size = 24,
  color = '#FFFFFF',
  accessibilityLabel,
  ...svgProps
}: LudoraIconProps) {
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      accessibilityRole="image"
      accessibilityLabel={accessibilityLabel}
      {...svgProps}
    >
      <Path fill={color} d="M21,19V20H3V19L5,17V11C5,7.9 7.03,5.17 10,4.29C10,4.19 10,4.1 10,4A2,2 0 0,1 12,2A2,2 0 0,1 14,4C14,4.1 14,4.19 14,4.29C16.97,5.17 19,7.9 19,11V17L21,19M14,21A2,2 0 0,1 12,23A2,2 0 0,1 10,21" />
    </Svg>
  );
}
