/* AUTO-GENERATED by scripts/generate-icons.mjs. Do not edit manually. */
import Svg, { Path } from 'react-native-svg';

import type { LudoraIconProps } from '../types';

export function CheckIcon({
  size = 24,
  color = '#FFFFFF',
  accessibilityLabel,
  ...svgProps
}: LudoraIconProps) {
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 -960 960 960"
      accessibilityRole="image"
      accessibilityLabel={accessibilityLabel}
      {...svgProps}
    >
      <Path fill={color} d="M382-240 154-468l57-57 171 171 367-367 57 57-424 424Z" />
    </Svg>
  );
}
