/* AUTO-GENERATED by scripts/generate-icons.mjs. Do not edit manually. */
import Svg, { Path } from 'react-native-svg';

import type { LudoraIconProps } from '../types';

export function HomeIcon({
  size = 24,
  color = '#FFFFFF',
  accessibilityLabel,
  ...svgProps
}: LudoraIconProps) {
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 -960 960 960"
      accessibilityRole="image"
      accessibilityLabel={accessibilityLabel}
      {...svgProps}
    >
      <Path fill={color} d="M240-200h120v-240h240v240h120v-360L480-740 240-560v360Zm-80 80v-480l320-240 320 240v480H520v-240h-80v240H160Zm320-350Z" />
    </Svg>
  );
}
