/* AUTO-GENERATED by scripts/generate-icons.mjs. Do not edit manually. */
import Svg, { Path } from 'react-native-svg';

import type { LudoraIconProps } from '../types';

export function PodiumIcon({
  size = 24,
  color = '#FFFFFF',
  accessibilityLabel,
  ...svgProps
}: LudoraIconProps) {
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 -960 960 960"
      accessibilityRole="image"
      accessibilityLabel={accessibilityLabel}
      {...svgProps}
    >
      <Path fill={color} d="M160-200h160v-320H160v320Zm240 0h160v-560H400v560Zm240 0h160v-240H640v240ZM80-120v-480h240v-240h320v320h240v400H80Z" />
    </Svg>
  );
}
